# Site settings
title: Community Leadership Summit Spain (CLSxSpain)
email: jsmanrique@bitergia.com
description: "Community Leadership Summit Spain brings together community leaders, organizers and managers and the projects and organizations that are interested in growing and empowering a strong community"
description_es: "El Community Leaderhsip Summit, edición España, agrupa líderes, gestores y organizadores de comunidades y los proyectos y organizaciones que están interesadas en hacer crecer y generar comunidades fuertes."
baseurl: ""
url: "http://www.clsxmadrid.es"
author: "Manrique Lopez"

include: [.htaccess]

# Build settings
markdown: kramdown
permalink: pretty
